spring.application.name=software01
spring.web.resources.static-locations=classpath:/static/,classpath:/public/,classpath:/resources/,classpath:/META-INF/resources/,file:/D:/images/
# 数据源配置

spring.datasource.url=jdbc:mysql://localhost:3306/moviedb?serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=123456
#spring.datasource.driver-class-name=com.mysql.jdbc.Driver

# Hibernate 配置
#spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.ddl-auto=none
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL57InnoDBDialect

# 显示 Hibernate 生成的 SQL
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.servlet.multipart.max-file-size=2MB
spring.servlet.multipart.max-request-size=10MB

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE